### ISSUE TITLE
Simple window.ai wrapper library in TypeScript

### ISSUE THREAD

**Issue by alexanderatallah** [alexanderatallah/window.ai#15]
We need a simple library in `packages/` that can be consumed by the `extension` and `web` apps. It should:

- be the source of truth for types, e.g. what the extension's `public-interface.ts` file does today
- allow developers to get types easily when making window.ai apps
- be very simple. Projects like https://github.com/haardikk21/wanda should be able to build on top of it
- throw `ErrorCode`s appropriately
- add an `ErrorCode` for when the extension is not installed (wait for a little bit after the document onload event before deciding)
- include examples of usage

**Comment by cfortuner** [comment]
Started work on this here https://github.com/alexanderatallah/window.ai/pull/17

Got this package -> https://www.npmjs.com/package/window.ai

**Comment by alexanderatallah** [comment]
Resolved by #17 - big thanks to @louisgv and @cfortuner, we now have an official lib! 📚
