### ISSUE TITLE
window.ai call hangs, extension doesn't ask for permission, for Three.js example

### ISSUE THREAD

**Issue by zoan37** [alexanderatallah/window.ai#69]
This is probably an edge case, but when trying to call window.ai in a Three.js demo example in the Three.js package, the window.ai call hangs, and the extension doesn't show a pop up asking for permission as expected. Confirmed this for the current Window build and the beta build with 3D object generation.

I'm not sure what is special about the Three.js demo that is leading to this behavior.

This is not blocking me because I'm planning to port that demo code to another repo.

Steps to reproduce:
* ```git clone --depth=1 https://github.com/zoan37/three.js.git``` (using --depth=1 avoids downloading all the history in three.js)
* 
```
git checkout -b window_possible_bug
git pull origin window_possible_bug
```
(the branch with the code changes I made)
* Run python server locally: ```python3 -m http.server```
* Visit: ```http://localhost:8000/examples/?q=fps#games_fps```
* As you can see in the console logs, window.ai is being called, but it hangs / no popup from the extension asking for permission.

**Comment by YanniKouloumbis** [comment]
Cloned the repo but I don't see a `window_possible_bug` branch, is it pushed?

**Comment by zoan37** [comment]
@YanniKouloumbis Oh, it is right here: https://github.com/zoan37/three.js/tree/window_possible_bug , hope that works

(btw I ported my code to a new repo with just the octree demo code and it's working there, funny this repo doesn't work)

**Comment by zoan37** [comment]
oh I'm getting same error when doing "git checkout window_possible_bug", i'll look into it

**Comment by zoan37** [comment]
Sorry, please run:

```
git checkout -b window_possible_bug
git pull origin window_possible_bug
```

instead of ```git checkout window_possible_bug``` as stated above.

**Comment by YanniKouloumbis** [comment]
If I run a sample command in the console I see the popup. Is there a way to reproduce the window.ai call?

<img width="610" alt="image" src="https://github.com/alexanderatallah/window.ai/assets/107221725/63e4e696-2db5-4346-9a8d-d26f3f208f2b">

**Comment by zoan37** [comment]
I found the issue, the example is displayed in an iframe! lol. sorry for the trouble!

**Comment by YanniKouloumbis** [comment]
No worries, glad it's all working! Closing this issue!
